[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "*.ttf"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "*.woff*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
